curl 'https://wabi-east-asia-a-primary-api.analysis.windows.net/public/reports/querydata?synchronous=true' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'sec-ch-ua: "Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36' \
  -H 'ActivityId: 544526b1-c20d-462b-b00b-cb0f6c7806f7' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'RequestId: 543fa36a-f69b-a1eb-7c37-29b39322b02a' \
  -H 'X-PowerBI-ResourceKey: 67891699-07a0-4c35-9021-ae10222241c0' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Origin: https://app.powerbi.com' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://app.powerbi.com/' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'dnt: 1' \
  -H 'sec-gpc: 1' \
  --data-binary $'{"version":"1.0.0","queries":[{"Query":{"Commands":[{"SemanticQueryDataShapeCommand":{"Query":{"Version":2,"From":[{"Name":"w","Entity":"WASTE 2020 TO 2025","Type":0}],"Select":[{"Column":{"Expression":{"SourceRef":{"Source":"w"}},"Property":"REGION"},"Name":"WASTE 2020 TO 2025.REGION"},{"Column":{"Expression":{"SourceRef":{"Source":"w"}},"Property":"PROVINCE"},"Name":"WASTE 2020 TO 2025.PROVINCE"},{"Column":{"Expression":{"SourceRef":{"Source":"w"}},"Property":"CITY/MUNICIPALITY"},"Name":"WASTE 2020 TO 2025.CITY/MUNICIPALITY"},{"Column":{"Expression":{"SourceRef":{"Source":"w"}},"Property":"PROJECTED WASTE (TONS/YEAR)"},"Name":"Sum(WASTE 2020 TO 2025.PROJECTED WASTE (TONS/YEAR))"},{"Column":{"Expression":{"SourceRef":{"Source":"w"}},"Property":"YEAR"},"Name":"WASTE 2020 TO 2025.YEAR"}]},"Binding":{"Primary":{"Groupings":[{"Projections":[0,1,2,3,4],"Subtotal":1}]},"DataReduction":{"DataVolume":3,"Primary":{"Window":{"Count":30000,"RestartTokens":[["'CAR'","'BENGUET'","'KABAYAN'","1880.6769574490204D","'2021'"]]}}},"Version":1},"ExecutionMetricsKind":1}}]},"QueryId":""}],"cancelQueries":[],"modelId":876505}'\
  --compressed | sed 's/"jobIds":\[[^]]*\],//g' | sed 's/"jobId":"[^"]*",//g' | sed 's/"rootActivityId":"[^"]*",//g' | sed 's/"timestamp":"[^"]*",//g' | jq '.' > "projected_waste_test2.json"